### ISSUE TITLE
[Suggestion] Add titles when entering structures

### ISSUE THREAD

**Issue by JorisDeBeer** [YUNG-GANG/Travelers-Titles#43] opened 2023-09-24 14:26 UTC
Could we get support for titles when entering things classified as structures? 

Would be cool to get villages names and fortress titles to display shortly when entering such a building. Very cool with your own structure mods too! 

Easy way I think is to use the minecraft predicate system.

**Comment by MrGreenTea** [comment] 2023-10-10 08:19
This is a duplicate of #8

**Closed as completed** 2023-10-17 20:10 UTC
Labels: duplicate
