### ISSUE TITLE
[Suggestion] Pop up names of structures as well as biomes

### ISSUE THREAD

**Issue by jlaine3333** [YUNG-GANG/Travelers-Titles#25] opened 2022-07-19 23:11 UTC
Sometimes, when entering a structure, I'd like to know what it's called. Having a title pop up would help and add atmosphere when I'm about to enter a dungeon or something.

**Comment by yungnickyoung** [comment] 2023-10-17 20:17
Duplicate of #8

**Closed as completed by yungnickyoung** 2023-10-17 20:17 UTC
Labels: duplicate
